version: 0.0
Resources:
  - TargetService:
      Type: AWS::Lambda::Function
      Properties:
        Name: mylambda
      Artifact:
        Location: lambda_function.zip
        S3Bucket: dafdfedfad
