version: 0.0
Resources:
  - TargetService:
      Type: AWS::Lambda::Function
      Properties:
        Name: "newpython"
        Alias: "python-alias"
        CurrentVersion: "1"
        TargetVersion: "*"
Hooks:
