version: 1.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "newpython"
        # Alias: "python-alias"
        # Update with the correct version based on your desired deployment behavior:
        CurrentVersion: "1"  # Replace with the specific version you want to deploy
        # OR
        TargetVersion: "*"  # Deploy to the latest published version

        # Additional properties as needed for your Lambda function

Hooks:
  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeTrafficShift"
  - AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"
