version: 0.0
os: linux
files:
  - source: /
    destination: /var/task
hooks:
  ApplicationStop:
    - location: stop_lambda.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: cleanup_lambda.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy_lambda.sh
      timeout: 300
      runas: root
