version: 0.0
os: linux
files:
  - source: /
    destination: /var/task

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: lambda-deploy.sh
      timeout: 300
      runas: root
