version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: MyLambdaFunction
        Alias: MyLambdaFunctionAlias
        # Use a placeholder for TargetVersion
        TargetVersion: PLACEHOLDER_FOR_TARGET_VERSION
        # CurrentVersion can be left empty
        # CurrentVersion: MyLambdaFunctionVersion
        DeploymentId: CodeDeployDeploymentId
hooks:
  - BeforeInstall:
      - location: scripts/before_install.sh
        runas: root
  - AfterInstall:
      - location: scripts/after_install.sh
        runas: root
