version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: newpython
        Alias: python-alias
hooks:
  # - BeforeInstall:
  #     - location: scripts/before_install.sh
  #       runas: root
  - AfterInstall:
      - location: scripts/after_install.sh
        runas: root
