version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo Build started on `date`
      - echo Installing dependencies...
      - pip install -r requirements.txt --target .
      - echo Creating build directory...
      - mkdir build
      - echo Copying appspec.yml to build directory...
      - cp appspec.yml build/
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
    - build/appspec.yml
