version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt -t .
      - ls
      - pwd
  build:
    commands:
      - echo "Building Lambda deployment package..."
      - ls
      - zip -r ../lambda_function.zip . -x "*.git*"
      - cd ..
      - ls
      - pwd
      - aws lambda update-function-code --function-name mylambda --zip-file fileb://lambda_function.zip
      - sleep 30
      - aws lambda invoke --function-name mylambda --payload file://event.json output.json
  post_build:
    commands:
      - echo "Lambda deployment package created successfully."
