version: 0.2

phases:
  build:
    commands:
      - git pull origin main # Ensure you have the latest changes from GitHub
      - zip -g deployment_package.zip lambda_function.py # Update the lambda_function.py in the deployment package
      # Add any other build commands here
  post_build:
    commands:
      - aws lambda update-function-code --function-name YourFunctionName --zip-file fileb://deployment_package.zip
      # Replace YourFunctionName with the actual name of your Lambda function
      # This command updates the Lambda function code with the contents of deployment_package.zip
      # Make sure to configure AWS CLI with appropriate credentials and region before running this command
artifacts:
  files:
    - deployment_package.zip # Include the deployment package as an artifact
