version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt -t build/
  build:
    commands:
      - cd build/
      - zip -r lambda_function.zip .
      - pwd
      - ls
artifacts:
  files:
    - /codebuild/output/src4290578079/src/build/lambda_function.zip