version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt -t build/
  build:
    commands:
      - echo "Building Lambda deployment package..."
      - cd build/
      - zip -r ../lambda_function.zip . -x "*.git*"
      - cd ..
      - ls
      - pwd
  post_build:
    commands:
      - echo "Lambda deployment package created successfully."
artifacts:
  files:
    - lambda_function.zip
